### ISSUE TITLE
error on /resource-nc/user/me for newly created user

### ISSUE THREAD

**Issue by berger-n** [buda-base/editserv#17]
on https://library.bdrc.io/ when registering a new user in Auth0 everything's fine and user seems to be successfully logged in
but when accessing user profile page there is a 500 error at https://editserv.bdrc.io/resource-nc/user/me :

![image](https://user-images.githubusercontent.com/33383857/115025902-2cf48b00-9ec2-11eb-93a8-a4a39c71315b.png)

stacktrace:

```
java.lang.NullPointerException: null
	at io.bdrc.edit.user.BudaUser.createBudaUserModels(BudaUser.java:249)
	at io.bdrc.edit.user.BudaUser.addNewBudaUser(BudaUser.java:350)
	at io.bdrc.edit.controllers.UserEditController.meUser(UserEditController.java:78)
```

**Edit:** it happens both with Gmail registering and Email-Password registering

**Comment by eroux** [comment]
can you test again?

**Comment by berger-n** [comment]
just created a new account, also tried again with previous ones, nothing changed so far

**Comment by eroux** [comment]
arf ok, thanks! new trace:

```
java.lang.NullPointerException: null lexical form for literal
	at org.apache.jena.graph.NodeFactory.createLiteral(NodeFactory.java:136)
	at org.apache.jena.rdf.model.ResourceFactory$Impl.createStringLiteral(ResourceFactory.java:302)
	at org.apache.jena.rdf.model.ResourceFactory.createPlainLiteral(ResourceFactory.java:107)
	at io.bdrc.edit.user.BudaUser.createBudaUserModels(BudaUser.java:285)
	at io.bdrc.edit.user.BudaUser.addNewBudaUser(BudaUser.java:322)
```

**Comment by eroux** [comment]
what about now? (you can try with the previous account that didn't work, no need to create a new one)

**Comment by berger-n** [comment]
now it works for Google-users 
but not for Email-Password-users

**Comment by eroux** [comment]
might be related to this mysterious stacktrace:

```
java.lang.StackOverflowError: null
	at java.text.DateFormatSymbols.<init>(DateFormatSymbols.java:145)
	at sun.util.locale.provider.DateFormatSymbolsProviderImpl.getInstance(DateFormatSymbolsProviderImpl.java:85)
	at java.text.DateFormatSymbols.getProviderInstance(DateFormatSymbols.java:364)
	at java.text.DateFormatSymbols.getInstance(DateFormatSymbols.java:340)
	at java.util.Calendar.getDisplayName(Calendar.java:2110)
	at java.text.SimpleDateFormat.subFormat(SimpleDateFormat.java:1125)
	at java.text.SimpleDateFormat.format(SimpleDateFormat.java:966)
	at java.text.SimpleDateFormat.format(SimpleDateFormat.java:936)
	at java.text.DateFormat.format(DateFormat.java:345)
	at ch.qos.logback.core.util.CachingDateFormatter.format(CachingDateFormatter.java:48)
	at ch.qos.logback.classic.pattern.DateConverter.convert(DateConverter.java:61)
	at ch.qos.logback.classic.pattern.DateConverter.convert(DateConverter.java:23)
	at ch.qos.logback.core.pattern.FormattingConverter.write(FormattingConverter.java:36)
	at ch.qos.logback.core.pattern.PatternLayoutBase.writeLoopOnConverters(PatternLayoutBase.java:115)
	at ch.qos.logback.classic.PatternLayout.doLayout(PatternLayout.java:141)
	at ch.qos.logback.classic.PatternLayout.doLayout(PatternLayout.java:39)
	at ch.qos.logback.core.encoder.LayoutWrappingEncoder.encode(LayoutWrappingEncoder.java:115)
	at ch.qos.logback.core.OutputStreamAppender.subAppend(OutputStreamAppender.java:230)
	at ch.qos.logback.core.rolling.RollingFileAppender.subAppend(RollingFileAppender.java:235)
	at ch.qos.logback.core.OutputStreamAppender.append(OutputStreamAppender.java:102)
	at ch.qos.logback.core.UnsynchronizedAppenderBase.doAppend(UnsynchronizedAppenderBase.java:84)
	at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:51)
	at ch.qos.logback.classic.Logger.appendLoopOnAppenders(Logger.java:270)
	at ch.qos.logback.classic.Logger.callAppenders(Logger.java:257)
	at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:421)
	at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:383)
	at ch.qos.logback.classic.Logger.error(Logger.java:538)
	at io.bdrc.edit.user.UserPatchModule.setStatus(UserPatchModule.java:133)
	at io.bdrc.edit.user.UserPatchModule.setStatus(UserPatchModule.java:134)
	at io.bdrc.edit.user.UserPatchModule.setStatus(UserPatchModule.java:134)
	at io.bdrc.edit.user.UserPatchModule.setStatus(UserPatchModule.java:134)
```

**Comment by berger-n** [comment]
Google-user cannot update data though, patch request hangs then show either some unknown "CORS error" or 500 error:

![image](https://user-images.githubusercontent.com/33383857/115047542-e78f8800-9ed8-11eb-9cc0-86569d3fd4b6.png)

![image](https://user-images.githubusercontent.com/33383857/115048283-aea3e300-9ed9-11eb-8f8a-653acf0f8923.png)

**Comment by berger-n** [comment]
now it does not hang anymore but stills fails on a 500 error:

![image](https://user-images.githubusercontent.com/33383857/115049584-2de5e680-9edb-11eb-8a1b-c2ae1427876c.png)

don't know if this is related but there is supposed to be an actual email property in user data:

![image](https://user-images.githubusercontent.com/33383857/115049905-81f0cb00-9edb-11eb-98f3-b90b72e99e74.png)

which there is not in my newly created Google-user:

![image](https://user-images.githubusercontent.com/33383857/115050137-b9f80e00-9edb-11eb-9a49-9319e15cbfaa.png)

**Comment by berger-n** [comment]
no more 500 error after registration of new email/password user
thanks a lot!
